services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_URI=${POSTGRES_URI}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - database
      - mongo
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules:cached

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # MongoDB port exposed for external access
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE} 
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
